spring:
  application:
    name: inerface-test-mock
  profiles:
    active: local

server:
  port: 28080
  servlet:
    context-path: /mock

grpc:
  server:
    port: 9096
  keepAliveTime: 6

nats:
  enable: true
  server: "nats://localhost:4222"
